Repository Poketnans/metamorfo-tattoo, pull requests merged in 2022-03, with the labels that each got.

#18 fix: tattoooists model refactored due to today's meeting
  app/models/tattooists_model.py
Labels: good first issue

#19 refactor model, add relationship Tatoo and TatooImages. Remove column…
  app/models/tattoos_model.py
Labels: good first issue

#20 feat: add two column (image_mimetype, image_name) and renamed image f…
  app/models/tattoo_images_model.py
Labels: good first issue

#21 fix: adjusting materials model before ER Diagram changes
  app/models/materials_model.py
Labels: good first issue

#12 feat: insert code basic controller create client
  app/controllers/clients_controllers/post_create.py
  app/errors/bad_requisition.py
  app/models/tattoos_model.py
  app/routes/__init__.py
  app/routes/orders_blueprint.py
Labels: bug

#38 Feature/get image client
  app/controllers/clients_controllers/__init__.py
  app/controllers/clients_controllers/get_image.py
  app/controllers/clients_controllers/update.py
  app/routes/clients_blueprint.py
Labels: bug

#37 Feature/controller tattoists get by
  app/controllers/tattooists_controllers/get_specific.py
  app/routes/tattooists_blueprint.py
Labels: bug

#41 refactor: add code for image and change message error
  app/controllers/clients_controllers/post_create.py
  app/errors/bad_requisition.py
Labels: pattern issue

#39 feat: get all tattoos working as expected
  app/controllers/tattoos_controllers/get_all.py
  app/models/tattoos_model.py
  app/routes/tattoos_blueprint.py
Labels: waiting

#42 feat: get specific tattoo working as expected
  app/controllers/tattoos_controllers/get_specific.py
  app/routes/tattoos_blueprint.py
Labels: waiting

#80 Fix/controller storage create
  app/controllers/storage_controllers/create.py
  app/decorators/validator.py
  app/decorators/verify_payload.py
  app/models/storage_model.py
  app/services/payload_eval.py
Labels: good first issue
